apiVersion: v1
kind: Namespace
metadata:
  name: rti-app
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: rti-app
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyA7WrPlV5Ogkhm7pZzdRJmd2HoUvrlq-Ro"
